# Generated by Django 4.1 on 2022-09-03 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='id',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='name',
        ),
        migrations.AddField(
            model_name='upload',
            name='photo_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
